### PR TITLE
[Rebase & FF] Refactor System Tables implementation to add resilience around external modification.

### LINKED ISSUE #1206: [Bug]: System Table structures are not guaranteed to be externally visible.
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

Under the present design point the system tables and config tables implementations do not use `volatile` access when producing, consuming, or modifying system tables (the main system table, runtime services table, boot services table, and various configuration tables). This means that changes to those tables from within patina core are not guaranteed to be externally observable (i.e. the compiler can make assumptions about those accesses that might mean they don't actually get written to system memory), and changes to the system tables from outside patina (such as installation of new function pointers in the runtime services table by e.g. VariableServices) are not guaranteed to be observed by patina.

Empirically, this works at the moment, but it is essentially UB in the sense that it could _not_ work under future compiler revisions or with changes in optimizations enabled etc. 

### Expected Behavior

External driver should observe all changes that are made to externally observable structures, and all changes made by external drivers to externally observable structures should be observed by Patina.  Present code does not guarantee this, although it works in practice. 

### Steps To Reproduce

By inspection.

### Build Environment

```markdown
N/A
```

### Version Information

```text
Commit: c28a32ab2435e58eb6b332bfbab03a476396910f
```

### Urgency

Medium

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joschock**
## Description

In the present design, the system table stores `&'static` references to the System Table, Boot Services Table, and Runtime Services table. These refs imply to the rust compiler that these tables are immutable, but in fact, they are mutated under these references by drivers external to patina (e.g. when the variable service driver installs its APIs into the runtime services table). 

This refactor changes the underlying static immutable references to these tables into raw pointers to better reflect the reality of the table usage and minimize UB due to immutable ref covering a data structure that is potentially mutated. Note that it doesn't entirely eliminate the UB, since to do so would place requirements for synchronization on those external agents, none of which currently implement those requirements.  

This is a breaking change since it changes the instantiation of SDK boot services and runtime services wrapper to take raw pointers rather than references.

This PR also brings in a secondary refactor of `core_install_configuration_table` to avoid an unnecessary "Box::from_raw" conversion on the table (this is a separate commit). This routine was being touched by the above refactor anyway so was convenient for the refactor. Rebase and FF to include these as two separate changes.

Closes #1206.

- [x] Impacts functionality?
- [ ] Impacts security?
- [x] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

Unit tests pass; live testing boots to OS without issues. 

## Integration Instructions

`StandardBootServices` and `StandardRuntimeServices` instantiations now take a raw pointer to the corresponding tables.

### CODE REVIEW

File: patina_dxe_core/src/protocols.rs [hunk 1]
```diff
@@ -797,13 +798,14 @@ extern "efiapi" fn locate_device_path(
...
+
     //This bit of trickery is needed because r_efi definition of (Un)InstallMultipleProtocolInterfaces
     //is not variadic, due to rust only supporting variadic for "unsafe extern C" and not "efiapi"
-    //until very recently. For x86_64 "efiapi" and "extern C" match, so we can get away with a
-    //transmute here. Fixing it for other architectures more generally would require an upstream
-    //change in r_efi to pick up. There is also a bug in r_efi definition for
-    //uninstall_multiple_program_interfaces - per spec, the first argument is a handle, but
+    //until rust 1.91. For our purposes "efiapi" and "extern C" match, so we can get away with a
+    //transmute here. Fixing it properly would require an upstream change in r_efi to pick up. There is also a bug in
+    //the r_efi definition for uninstall_multiple_protocol_interfaces - per spec, the first argument is a handle, but
```
Comment (os-d) [inline patina_dxe_core/src/protocols.rs:808]: Do we have a task for fixing this? Seems like it should be pretty non-controversial to fix and we should...can you file a task if there isn't one?

File: patina_dxe_core/src/runtime.rs [hunk 2]
```diff
@@ -68,7 +70,7 @@ impl RuntimeData {
     }
 }
 
-pub fn init_runtime_support(_rt: &mut efi::RuntimeServices) {
+pub fn init_runtime_support(_st: &mut EfiSystemTable) {
```
Comment (os-d) [inline patina_dxe_core/src/runtime.rs]: Just drop the param since it is unused?

File: patina_dxe_core/src/systemtables.rs [hunk 3]
```diff
@@ -20,708 +20,848 @@ pub static SYSTEM_TABLE: tpl_mutex::TplMutex<Option<EfiSystemTable>> =
...
     #[allow(dead_code)]
-    pub fn system_table(&self) -> &efi::SystemTable {
-        self.system_table.as_ref()
+    /// Creates a new EFI System Table instance from the given raw pointer.
+    /// # Safety
+    /// The pointer must be valid and point to a properly initialized efi::SystemTable structure.
+    pub unsafe fn from_raw_pointer(ptr: *mut efi::SystemTable) -> Self {
+        unsafe {
+            assert!(
+                !(*ptr).boot_services.is_null(),
```
Comment (os-d) [inline patina_dxe_core/src/systemtables.rs:720]: Check if ptr is null before dereferencing?

File: patina_dxe_core/src/systemtables.rs [hunk 4]
```diff
@@ -20,708 +20,848 @@ pub static SYSTEM_TABLE: tpl_mutex::TplMutex<Option<EfiSystemTable>> =
...
     }
 
-    pub fn runtime_services_mut(&mut self) -> &mut efi::RuntimeServices {
-        // SAFETY: runtime_services pointer in the system table is valid once system table is constructed.
-        // Note: this creates a mutable reference to the runtime services pointer. The function should be marked unsafe
-        // since the caller needs to ensure that no other references to runtime services exist when this is called.
-        // Issue: #1200
-        unsafe { self.system_table.runtime_services.as_mut().expect("RuntimeServices uninitialized") }
+    /// Returns the raw pointer to the System Table.
+    pub fn as_ptr(&self) -> *mut efi::SystemTable {
```
Comment (os-d) [inline patina_dxe_core/src/systemtables.rs]: nit: this seems like it would be a bit more canonical and useful to be `as_mut_ptr`

File: patina_dxe_core/src/systemtables.rs [hunk 5]
```diff
@@ -20,708 +20,848 @@ pub static SYSTEM_TABLE: tpl_mutex::TplMutex<Option<EfiSystemTable>> =
...
+
+        st.boot_services = core::ptr::null_mut();
+        st.con_in = core::ptr::null_mut();
+        st.console_in_handle = core::ptr::null_mut();
+        st.con_out = core::ptr::null_mut();
+        st.console_out_handle = core::ptr::null_mut();
+        st.std_err = core::ptr::null_mut();
+        st.standard_error_handle = core::ptr::null_mut();
+
+        // SAFETY: this
```
Comment (os-d) [inline patina_dxe_core/src/systemtables.rs]: didn't finish comment

File: sdk/patina/src/boot_services.rs [hunk 6]
```diff
@@ -79,8 +79,21 @@ impl StandardBootServices {
         self.efi_boot_services.is_completed()
     }
 
-    fn efi_boot_services(&self) -> &efi::BootServices {
-        self.efi_boot_services.get().expect("Standard Boot Services is not initialized!")
+    // Returns the boot services pointer if initialized, panics otherwise.
+    fn as_ptr(&self) -> *mut efi::BootServices {
```
Comment (os-d) [inline sdk/patina/src/boot_services.rs]: Same comment on naming

File: sdk/patina/src/boot_services.rs [hunk 7]
```diff
@@ -79,8 +79,21 @@ impl StandardBootServices {
...
+        *self.efi_boot_services.get().expect("Standard Boot Services is not initialized!")
+    }
+
+    // returns the boot services as a static reference, panics if uninitialized.
+    // SAFETY: This is unsafe because the boot services structure may be subject to external mutation.
+    // In most use cases, this should not be an issue as external code does not typically mutate the boot services
+    // struct except in certain well-defined cases (e.g. MonotonicCount and CalculateCrc32 API installations into the
+    // boot services struct), and it is expected that those modifications will be targeted and not affect the usage of
+    // thestatic reference. If mutation does occur, however, it is technically UB, and this is marked unsafe to
```
Comment (os-d) [inline sdk/patina/src/boot_services.rs]: // the static

File: sdk/patina/src/boot_services.rs [hunk 8]
```diff
@@ -79,8 +79,21 @@ impl StandardBootServices {
...
 
-    fn efi_boot_services(&self) -> &efi::BootServices {
-        self.efi_boot_services.get().expect("Standard Boot Services is not initialized!")
+    // Returns the boot services pointer if initialized, panics otherwise.
+    fn as_ptr(&self) -> *mut efi::BootServices {
+        *self.efi_boot_services.get().expect("Standard Boot Services is not initialized!")
+    }
+
+    // returns the boot services as a static reference, panics if uninitialized.
+    // SAFETY: This is unsafe because the boot services structure may be subject to external mutation.
```
Comment (os-d) [inline sdk/patina/src/boot_services.rs]: I'm not sure I'm quite following along with marking this unsafe or why it is UB if another entity updates the table. Technically, that could happen with any of our memory (and we of course have many patterns of sharing memory with other non-Patina components). But in this case, I don't feel like the caller of the function has anything to uphold here, so I don't feel it makes sense to mark the function unsafe. The caller of the function can't ensure anything about the boot services table, it is simply asking the pointer it has for a mutable reference. That's legitimate to do, even if the table has been mutated by another entity, it would just be one of the fields has a different value now, but we've made the pointer and reference mutable, so that should be anticipated.

That being said, I don't feel strongly on this, just reading through the comment it didn't seem to meet the standard for marking a function unsafe.

File: sdk/patina/src/boot_services.rs [hunk 9]
```diff
@@ -106,57 +119,62 @@ impl Debug for StandardBootServices {
...
-            .field("get_next_monotonic_count", &(self.efi_boot_services().get_next_monotonic_count))
-            .field("install_configuration_table", &(self.efi_boot_services().install_configuration_table))
-            .field("calculate_crc32", &(self.efi_boot_services().calculate_crc32))
-            .finish()
+        // SAFETY: efi_boot_services() is unsafe to mark it as potentially subject to external mutation. If that were
+        // to happen during the debug formatting, the worst that could happen is that the debug output would be
+        // incorrect.
+        unsafe {
+            f.debug_struct("StandardBootServices")
+                .field("create_event", &(self.efi_boot_services().create_event))
```
Comment (os-d) [inline sdk/patina/src/boot_services.rs]: Just call efi_boot_services once?

File: sdk/patina/src/boot_services.rs [hunk 10]
```diff
@@ -1421,7 +1469,8 @@ impl BootServices for StandardBootServices {
     ) -> Result<BootServicesBox<'_, [&'static efi::Guid], Self>, efi::Status> {
         let mut protocol_buffer = ptr::null_mut();
         let mut protocol_buffer_count = 0;
-        match efi_boot_services_fn!(self.efi_boot_services(), protocols_per_handle)(
+        // SAFETY: assume that boot services struct is not being externally modified while in use.
```
Comment (os-d) [inline sdk/patina/src/boot_services.rs]: All of these go back to my point that there is nothing for a caller to do but say, well, I hope no one else is modifying the table, but again, that's true of all structures, to some degree. Doesn't seem like it adds value because there is nothing actionable or even to make sure the caller thinks about when calling this.

File: sdk/patina/src/runtime_services.rs [hunk 11]
```diff
@@ -63,9 +63,21 @@ impl StandardRuntimeServices {
         self.efi_runtime_services.is_completed()
     }
 
-    fn efi_runtime_services(&self) -> &efi::RuntimeServices {
-        // SAFETY: Runtime services lifetime is expected to live long enough.
-        self.efi_runtime_services.get().expect("Standard Runtime Services is not initialized!")
+    /// Returns the Runtime Services pointer. Panics if uninitialized.
+    pub fn as_ptr(&self) -> *mut efi::RuntimeServices {
```
Comment (os-d) [inline sdk/patina/src/runtime_services.rs]: Same naming comment

File: sdk/patina/src/runtime_services.rs [hunk 12]
```diff
@@ -63,9 +63,21 @@ impl StandardRuntimeServices {
...
+        *self.efi_runtime_services.get().expect("Standard Runtime Services is not initialized!")
+    }
+
+    // returns the runtime services as a static reference, panics if uninitialized.
+    // SAFETY: This is unsafe because the runtime services structure may be subject to external mutation.
```
Comment (os-d) [inline sdk/patina/src/runtime_services.rs]: Same unsafe comment

File: sdk/patina/src/runtime_services.rs [hunk 13]
```diff
@@ -93,22 +105,26 @@ impl Debug for StandardRuntimeServices {
...
-            .field("reset_system", &(self.efi_runtime_services().reset_system))
-            .field("get_next_high_mono_count", &(self.efi_runtime_services().get_next_high_mono_count))
-            .field("update_capsule", &(self.efi_runtime_services().update_capsule))
-            .finish()
+        // SAFETY: efi_runtime_services() is unsafe to mark it as potentially subject to external mutation. If that were
+        // to happen during the debug formatting, the worst that could happen is that the debug output would be
+        // incorrect.
+        unsafe {
+            f.debug_struct("StandardRuntimeServices")
+                .field("get_variable", &(self.efi_runtime_services().get_variable))
```
Comment (os-d) [inline sdk/patina/src/runtime_services.rs]: Call efi_runtime_services once?

File: patina_dxe_core/src/protocols.rs (hunk 1 above)
Comment (joschock) [reply patina_dxe_core/src/protocols.rs:808]: I think #806 covers it.

File: patina_dxe_core/src/runtime.rs (hunk 2 above)
Comment (joschock) [reply patina_dxe_core/src/runtime.rs]: happy to do so, following prior art here.

File: patina_dxe_core/src/systemtables.rs (hunk 4 above)
Comment (joschock) [reply patina_dxe_core/src/systemtables.rs]: I actually spent some time looking for prior art before picking the name. It's rather ambiguous: https://internals.rust-lang.org/t/as-ptr-vs-as-mut-ptr/9940, so I picked the one that seemed most consistent with other usages. But frankly, I'm happy to go either way, my preference strength on the name here is basically zero.

File: sdk/patina/src/boot_services.rs (hunk 8 above)
Comment (joschock) [reply sdk/patina/src/boot_services.rs]: The reason it is unsafe IMHO is because it is UB for memory to mutate behind a shared reference: https://doc.rust-lang.org/reference/behavior-considered-undefined.html#r-undefined.immutable. It's also UB because non-patina drivers writing the shared struct without synchronization technically cause a data race (another bullet on same list). I think both of those apply even if the "other party" doing the mutating is not rust - the compiler is still entitled to make potentially wrong assumptions based on the existence of the shared ref and the implied immutability of the struct that it refs.  

It is _not_ UB for other drivers to mutate the boot services table if no shared references to it exist (one of the main points of this PR is to get rid of long-lived shared references and replace them with raw pointers precisely to avoid that). But this function creates such a shared reference and thus opens a window to UB. 

As far as the caller not being able to do anything about that - the caller _could_ ensure that no mutation could occur on the external table e.g. by raising TPL to TPL_HIGH to kill concurrency.  IMHO doing so is an unnecessary level of paranoia (and also would make using these APIs really a pain), but I don't think it changes the unsafety of the function here, and I do want to make consumers of this function think about the fact that the table could (in theory) change out from under them. 

So - since the function opens a potential for UB that the caller should be cognizant of, I think unsafe is justified here.

File: sdk/patina/src/boot_services.rs (hunk 10 above)
Comment (joschock) [reply sdk/patina/src/boot_services.rs]: Here the safety comment is referring to the fact that we only need the table to not be modified while the shared ref exists, which is for the short lifetime of the wrapper function so we can get the function pointer to the call to the actual API. 

Truly paranoid code would look like:
```rust
let old_tpl = core_raise_tpl(TPL_HIGH)
let my_function_ptr = self.efi_boot_services().protocols_per_handle;
core_restore_tpl(old_tpl);
my_function_ptr(<whatever>)
```

I think that's unnecessary and pedantic because all current external writes I could find wouldn't break that assumption.  But the safety comment is essentially documenting that assumption that's required for correct code. 

To your point, I could move all this assumption documentation into the `efi_boot_services()` function that generates the ref; but I didn't do that because I think dangerous usages of that function are possible - for example, grabbing a 'static shared ref from that function and caching it in a global static is probably not a good idea.

Comment (joschock) [reply sdk/patina/src/boot_services.rs]: I also had an iteration where I removed `efi_boot_services` altogether and forced all callers to deal directly with the *mut efi::BootServices. But that results in the same amount of unsafe blocks, tho IMHO it removes one of the two unsafety issues (the compiler no longer has a shared ref that allows it to assume immutability). I'm still not fully convinced that the shared ref does much but make things more unsafe here, so I could be convinced to remove it.

File: sdk/patina/src/boot_services.rs (hunk 8 above)
Comment (joschock) [reply sdk/patina/src/boot_services.rs]: A toy example of what I'm worried about. This doesn't exist today, but demos my concerns.

```rust
let my_bs_ref = my_standard_boot_serices.efi_boot_services();
my_bs_ref.start_image(runtime_dxe); // installs a new pointer in gBS->CalculateCrc32
let my_calc32 = my_bs_ref.calculate_crc32;
my_calc32 (buffer);
```

The compiler believes `my_bs_ref` is immutable. So it could reorder the read of the function pointer for calculate_crc32() - not the call, but the function pointer read from `my_bs_ref` - _before_ the `start_image` call that changes the function pointer. If it did such a re-ordering the call to calculate_crc32 would go to the old crc function rather than the one that was installed by runtime_dxe. I speculate that it might even be able to re-order the whole `my_calc32` call before `start_image`, if it is convinced that `start_image` won't modify `my_bs_ref` or `buffer`.  I don't believe that's the case because those calls are both externs, and I don't think you can re-order externs. But I'm not certain about that.

Again, I don't think this can happen with current implementations that I'm aware of, and I also can't imagine why such a reordering would occur - but the point is, _it could_ and it would not violate the language spec as I understand it (which also might not be the correct understanding - but this PR is a good place for enlightenment on that point - so if I've got it wrong, please help me understand what I'm missing here).

File: sdk/patina/src/boot_services.rs (hunk 10 above)
Comment (os-d) [reply sdk/patina/src/boot_services.rs]: Yeah, I mean from your description I would lean towards the path of removing the shared immutable ref at all (or make it mutable, though obviously that becomes a pain to use). Especially as patina should really not use the boot services table except to set it up (i.e. mutate it). Runtime services we are stuck with for longer, but still probably not long term, in terms of patina calling usage. But I think if we are concerned about the UB here, we should just eliminate the possibility, from the provided API anyway.

File: patina_dxe_core/src/systemtables.rs (hunk 4 above)
Comment (os-d) [reply patina_dxe_core/src/systemtables.rs]: Eh, yeah, reading that, either way I guess. To me personally it doesn’t make sense to say the mut in the name is whether you have &self or &mut self, at least in the form of as: mut ptr. That to me is what you are returning. If you had mut: as ptr, that would read as &mut self. But its all semantics. Feel free to close it or change it if anyone else has an opinion. Part of the weirdness, is it is clear cut if you also have a as_ptr, that returns the immutable version. So if you have as_ptr return a mut, later need to add an as_ptr that return an immutable ptr, you’ve just broken all consumers.

File: sdk/patina/src/boot_services.rs (hunk 8 above)
Comment (os-d) [reply sdk/patina/src/boot_services.rs]: No, I think your point is fair, but as mentioned above, I think the answer is to drop the shared ref and prevent this (from the API side, a caller can do whatever they want).

My main thing about making the function unsafe is that to me is if the caller needs to validate the invariants of calling the function, which in this case they don’t. Calling the function is always safe. The unsafety part here is something downstream could happen you don’t expect. But the function itself is not unsafe. So it is semantics, but then again what do we do but semantics :)

The [Rust docs](https://doc.rust-lang.org/std/keyword.unsafe.html) say:

unsafe fn: calling this function means abiding by a contract the
compiler cannot enforce.

Which to that definition, this fn is not unsafe. Calling the fn does not require any contract the compiler can’t enforce, i.e. the function itself has no UB. It’s later the UB occurs.

File: sdk/patina/src/boot_services.rs (hunk 10 above)
Comment (joschock) [reply sdk/patina/src/boot_services.rs]: Ok, I'll see about removing it. This is in the SDK, so it's more of an abstraction for components or external crates. Patina itself doesn't use it and generally just directly calls the internal boot services APIs. This is private to the impl, though, so removing it only affects the private code in these modules.

File: sdk/patina/src/boot_services.rs (hunk 8 above)
Comment (joschock) [reply sdk/patina/src/boot_services.rs]: The contract is "you have to ensure no one else modifies boot services".  This is technically achievable. But it also makes the shared ref basically useless and defeats the point of the function, I guess. I'm swayed to just remove it and let the caller deal with the raw pointer.

File: patina_dxe_core/src/config_tables.rs [hunk 14]
```diff
@@ -50,81 +50,74 @@ pub fn core_install_configuration_table(
...
-                if let Some(entry) = existing_entry {
-                    //entry exists, modify it.
-                    old_vendor_table_ptr = NonNull::new(entry.vendor_table);
-                    entry.vendor_table = vendor_table;
-                } else {
-                    //entry doesn't exist, add it.
-                    current_table.push(efi::ConfigurationTable { vendor_guid, vendor_table });
-                }
+    let (updated_table, old_vendor_table_ptr) = match system_table.configuration_table {
+        x if x.is_null() => {
```
Comment (Javagedes) [inline patina_dxe_core/src/config_tables.rs]: nit: I think we can use something other than `x` for the variable name :)

File: patina_dxe_core/src/systemtables.rs [hunk 15]
```diff
@@ -20,708 +20,851 @@ pub static SYSTEM_TABLE: tpl_mutex::TplMutex<Option<EfiSystemTable>> =
...
-            set_timer: Self::set_timer_unimplemented,
-            wait_for_event: Self::wait_for_event_unimplemented,
-            signal_event: Self::signal_event_unimplemented,
-            close_event: Self::close_event_unimplemented,
-            check_event: Self::check_event_unimplemented,
-            install_protocol_interface: Self::install_protocol_interface_unimplemented,
-            reinstall_protocol_interface: Self::reinstall_protocol_interface_unimplemented,
-            uninstall_protocol_interface: Self::uninstall_protocol_interface_unimplemented,
-            handle_protocol: Self::handle_protocol_unimplemented,
+            raise_tpl: raise_tpl_unimplemented,
```
Comment (Javagedes) [inline patina_dxe_core/src/systemtables.rs:632]: nit: why move these EFIAPI functions out of the impl? While I'm not against it - it is basically a no-op, it feels out of place in this PR.

File: sdk/patina/src/boot_services.rs [hunk 16]
```diff
@@ -45,19 +45,19 @@ use tpl::{Tpl, TplGuard};
 
 /// This is the boot services used in the UEFI.
 pub struct StandardBootServices {
-    efi_boot_services: Once<&'static efi::BootServices>,
+    efi_boot_services: Once<*mut efi::BootServices>,
```
Comment (Javagedes) [inline sdk/patina/src/boot_services.rs:48]: This seems like a safety degradation and more likely to lead to UB. Now we can pass it any pointer with any lifetime and cannot guarantee it will be valid for the lifetime of this StandardBootServices struct.

The underlying data could be reclaimed and reused and we would never know.

**Review by Javagedes — COMMENTED** [review]
Overall this looks fine for trying to tell the compiler this is mutable, to prevent updates being optimized away.

File: sdk/patina/src/boot_services.rs (hunk 16 above)
Comment (Javagedes) [reply sdk/patina/src/boot_services.rs:48]: `Box::leak` returns a &'static mut. I feel like we could update the interface to be `Once<&'static mut efi::BootServices>` or something with a variable lifetime for tests like

```rust
pub struct StandardBootServices<'a> {
  efi_boot_services: Once<&'a mut efi::BootServices>
}
```

File: patina_dxe_core/src/systemtables.rs (hunk 15 above)
Comment (joschock) [reply patina_dxe_core/src/systemtables.rs:632]: primary motivation is to make them as private as possible. I don't think they should be part of the impl because they are never intended to be directly called except thru the system table that is being constructed by the function I moved them into. Mostly done as part of general cleanup since I'm refactoring most of the file anyway.

File: sdk/patina/src/boot_services.rs (hunk 16 above)
Comment (joschock) [reply sdk/patina/src/boot_services.rs:48]: The main point of this PR is to avoid UB caused by lying to the compiler by giving it a long-lived reference to these tables. 

That ref means that the compiler can assume things about the backing table i.e. - for shared ref it can assume it never changes (so it can reorder/reads/writes/etc). For mut ref, more subtle, but it can assume that no changes happen to the table that it (the rust compiler) is not aware of.

That's simply not true because it's a spec-defined global table with existing art that is mutating it outside Patina. In practice it works, because our guesses/intuition (informed by c pointer behavior) about how the compiler handles these refs tend to align with the implementation-specific reality today, and external mutation of the tables is fairly limited in scope. But it's still UB. 

If the tables were completely under Patina control (by which I mean Patina was the only thing that was allowed, by spec, to read/write them), then it would be a different story. That would require some pretty significant arch changes to the UEFI spec tho.

File: sdk/patina/src/boot_services.rs (hunk 10 above)
Comment (joschock) [reply sdk/patina/src/boot_services.rs]: I've removed the ref generation functions; I do agree this is cleaner.

File: sdk/patina/src/boot_services.rs (hunk 8 above)
Comment (joschock) [reply sdk/patina/src/boot_services.rs]: function's removed.

File: components/patina_mm/src/component/communicator/comm_buffer_update.rs [hunk 17]
```diff
@@ -298,10 +298,10 @@ mod tests {
         communicator_ptr: *const MmCommunicator,
     ) -> Box<ProtocolNotifyContext> {
         let mock_bs = Box::leak(Box::new([0u8; core::mem::size_of::<r_efi::system::BootServices>()]));
-        let bs_ptr = mock_bs.as_ptr() as *const r_efi::system::BootServices;
+        let bs_ptr = mock_bs.as_mut_ptr() as *mut r_efi::system::BootServices;
         // SAFETY: bs_ptr points to an aligned mock buffer that was just created.
```
Comment (cfernald) [inline components/patina_mm/src/component/communicator/comm_buffer_update.rs]: Safety comment shouldnt be needed anymore.

File: patina_dxe_core/src/systemtables.rs [hunk 18]
```diff
@@ -20,708 +20,851 @@ pub static SYSTEM_TABLE: tpl_mutex::TplMutex<Option<EfiSystemTable>> =
...
+        unsafe { self.runtime_services.write(table_copy) }
     }
 
-    #[coverage(off)]
-    extern "efiapi" fn convert_pointer_unimplemented(_: usize, _: *mut *mut c_void) -> efi::Status {
-        efi::Status::from_usize(EFI_NOT_AVAILABLE_YET)
+    // Used in tests and included for API completness; may be used in future.
+    #[allow(dead_code)]
+    /// Returns a copy of the Runtime Services table.
+    pub fn get(&self) -> efi::RuntimeServices {
```
Comment (cfernald) [inline patina_dxe_core/src/systemtables.rs:61]: Should we provide getters/setters for individual fields? 

Or perhaps there is some `Deref`/`DerefMut` trait fanciness that can be done to avoid compiler assumptions without having to copy the whole table every access.

Comment (joschock) [reply patina_dxe_core/src/systemtables.rs:61]: I thought about this; but in general where this is used is typically a one-and-done scenario, so not really a perf hot path. Where it _is_ potentially a hot path (e.g. in StandardBootServices->callsomething called in a tight loop or something)  then we use a raw dereference. 

So not opposed to something fancy, but didn't really see the need.
