### PR TITLE
dxe_core: Move runtime event handling into runtime module

### LINKED ISSUE #337: [Bug]: Crash in set_virtual_address_map
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

There is a periodic crash in set_virtual_address_space map with the following signature:

```
INFO - EBS completed successfully. # Note this is a print about to be added
ERROR - panicked at C:\Users\olsmithd\.rustup\toolchains\1.84.0-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\collections\btree\node.rs:863:9:
assertion failed: idx <= node.len()
INFO - Dumping stack trace with PC: 0x7ea0eadf, SP: 0xffffffffaac039a0
INFO -       # Child-SP              Return Address         Call Site
INFO -       0 FFFFFFFFAAC039A0      000000007E9B41D1       qemu_q35_dxe_core-657b42e768b0b19e+69ADF
INFO -       1 FFFFFFFFAAC039D0      000000007EA9AF1F       qemu_q35_dxe_core-657b42e768b0b19e+F1D1
INFO -       2 FFFFFFFFAAC03AC0      000000007EA9AFC9       qemu_q35_dxe_core-657b42e768b0b19e+F5F1F
INFO -       3 FFFFFFFFAAC03B00      000000007EA51A5F       qemu_q35_dxe_core-657b42e768b0b19e+F5FC9
INFO -       4 FFFFFFFFAAC03B70      000000007EA2E65C       qemu_q35_dxe_core-657b42e768b0b19e+ACA5F
INFO -       5 FFFFFFFFAAC03BA0      000000007EA2F2B7       qemu_q35_dxe_core-657b42e768b0b19e+8965C
INFO -       6 FFFFFFFFAAC03C70      000000007E9F68A9       qemu_q35_dxe_core-657b42e768b0b19e+8A2B7
INFO -       7 FFFFFFFFAAC03D30      FFFFFFFFA86F0818       qemu_q35_dxe_core-657b42e768b0b19e+518A9
```

Which when run through the stacktrace script gives:

```
 # Source Path                                                           Child-SP         Return Address   Call Site
 0 [C:\Users\olsmithd\.cargo\registry\src\pkgs.dev.azure.com-f1ddb803f8268cb0\stacktrace-10.0.3\src\stacktrace.rs @  115] FFFFFFFFAAC039A0 000000007E9B41D1 qemu_q35_dxe_core-657b42e768b0b19e!union enum2$<core::result::Result<tuple$<>,enum2$<stacktrace::error::Error> > > stacktrace::stacktrace::StackTrace::dump()+F
 1 [d:\mu\mu_dev\qemu_rust_bins\bin\q35_dxe_core.rs              @   24] FFFFFFFFAAC039D0 000000007EA9AF1F qemu_q35_dxe_core-657b42e768b0b19e!void qemu_q35_dxe_core::panic(struct core::panic::panic_info::PanicInfo *)+D1
 2 [C:\Users\olsmithd\.rustup\toolchains\1.84.0-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\panicking.rs @   76] FFFFFFFFAAC03AC0 000000007EA9AFC9 qemu_q35_dxe_core-657b42e768b0b19e!void core::panicking::panic_fmt(struct core::fmt::Arguments, struct core::panic::location::Location *)+1F
 3 [C:\Users\olsmithd\.rustup\toolchains\1.84.0-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\panicking.rs @  148] FFFFFFFFAAC03B00 000000007EA51A5F qemu_q35_dxe_core-657b42e768b0b19e!void core::panicking::panic(struct ref$<str$>, struct core::panic::location::Location *)+49
 4 [C:\Users\olsmithd\.rustup\toolchains\1.84.0-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\collections\btree\navigate.rs @  559] FFFFFFFFAAC03B70 000000007EA2E65C qemu_q35_dxe_core-657b42e768b0b19e!struct tuple$<ref$<usize>,ref_mut$<dxe_core::event_db::Event> > alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::ValMut,usize,dxe_core::event_db::Event,enum2$<alloc::collections::btree::node::marker::Leaf> >,enum2$<alloc::collections::btree::node::marker::Edge> >::next_unchecked<usize,dxe_core::event_db::Event>()+6F
 5 [D:\mu\mu_dev\uefi-dxe-core\dxe_core\src\event_db.rs          @  342] FFFFFFFFAAC03BA0 000000007EA2F2B7 qemu_q35_dxe_core-657b42e768b0b19e!void dxe_core::event_db::EventDb::signal_group(struct r_efi::base::Guid)+10C
 6 [D:\mu\mu_dev\uefi-dxe-core\dxe_core\src\event_db.rs          @  594] FFFFFFFFAAC03C70 000000007E9F68A9 qemu_q35_dxe_core-657b42e768b0b19e!void dxe_core::event_db::SpinLockedEventDb::signal_group(struct r_efi::base::Guid)+87
 7 [D:\mu\mu_dev\uefi-dxe-core\dxe_core\src\runtime.rs           @   87] FFFFFFFFAAC03D30 FFFFFFFFA86F0818 qemu_q35_dxe_core-657b42e768b0b19e!static struct r_efi::base::Status dxe_core::runtime::set_virtual_address_map(unsigned __int64, unsigned __int64, unsigned int, struct r_efi::system::MemoryDescriptor *)+F9
```

### Expected Behavior

We should not crash in set_virtual_address_map

### Steps To Reproduce

Boot top of tree of all repos to Linux. Occasionally we will hit this.

### Build Environment

```markdown
- OS(s): Linux
- Tool Chain(s):
- Targets Impacted:
```

### Version Information

```text
top of tree
```

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cfernald**
## Description

This commit moves the handling of runtime events into the runtime.rs module and allocates them out of runtime memory. Runtime events, by definition and standard, are intended to be allocated in runtime memory and handled by a runtime driver. Since Patina handles the set_virtual_address_map itself, it must try to isolate that logic as much as possible from leveraging boot services resources.

This commit specifically resolves an issue on Windows where the set virtual address map is not called from the full firmware context. In this seperate context, the runtime services memory is mapped, but newer boot services data allocations may not be mapped. Moving the allocations to runtime memory works around potential access violations when traversing the tree that contains events that may have been allocated from a later heap.

CLOSES #337 

- [x] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

Boot to Windows on Q35

## Integration Instructions

N/A

### CODE REVIEW

File: patina_dxe_core/src/runtime.rs [hunk 1]
```diff
@@ -42,7 +43,12 @@ impl RuntimeData {
 unsafe impl Sync for RuntimeData {}
 unsafe impl Send for RuntimeData {}
 
+unsafe impl Sync for crate::event_db::Event {}
```
Comment (Javagedes) [inline patina_dxe_core/src/runtime.rs]: This should be implemented in the same place `Event` is defined. Also, this is an unsafe implementation, so you need to describe what makes this structure safe to send and update asynchronously.

File: patina_dxe_core/src/runtime.rs [hunk 2]
```diff
@@ -42,7 +43,12 @@ impl RuntimeData {
...
+unsafe impl Send for crate::event_db::Event {}
+
 static RUNTIME_DATA: Mutex<RuntimeData> = Mutex::new(RuntimeData::new());
+static RUNTIME_EVENTS: Mutex<BTreeMap<usize, crate::event_db::Event, &'static crate::allocator::UefiAllocator>> =
```
Comment (Javagedes) [inline patina_dxe_core/src/runtime.rs:47]: Is there any reason _not_ to add this to the existing runtime data structure? It seems like it would be better to reduce the number of statics we have.

Additionally, in the C code, the events get added to the event list inside the runtime protocol. Are there any additional concerns that we are not doing that, and instead have a different structure?

File: patina_dxe_core/src/event_db.rs [hunk 3]
```diff
@@ -188,17 +188,17 @@ impl Eq for TaggedEventNotification {}
 // whereas efi::Event is used as the public index or handle into the event database.
 // In the code below efi::Event is used to qualify the index/handle type, where as `Event` with
 // scope qualification refers to this private type.
-struct Event {
-    event_id: usize,
-    event_type: EventType,
-    event_group: Option<efi::Guid>,
+pub(crate) struct Event {
+    pub event_id: usize,
```
Comment (Javagedes) [inline patina_dxe_core/src/event_db.rs]: It does not look like all of the attributes here need to be pub. maybe a few of them, but those can be `inline(always)` functions. instead of direct access to them.

File: patina_dxe_core/src/runtime.rs (hunk 2 above)
Comment (makubacki) [reply patina_dxe_core/src/runtime.rs:47]: I believe the idea was to eliminate dependency on C-like and protocol structures where possible. C uses the protocol to communicate between two binaries - RuntimeDxe and the DXE Core and we don't need to do that.

File: patina_dxe_core/src/event_db.rs [hunk 4]
```diff
@@ -280,6 +280,9 @@ struct EventDb {
 }
 
 impl EventDb {
+    /// Tag used to runtime event IDs.
```
Comment (makubacki) [inline patina_dxe_core/src/event_db.rs]:
```suggestion
    /// Tag used for runtime event IDs.
```

File: patina_dxe_core/src/event_db.rs [hunk 5]
```diff
@@ -292,16 +295,38 @@ impl EventDb {
...
+            self.events.insert(id, event);
+        }
+
         Ok(id as efi::Event)
     }
 
     fn close_event(&mut self, event: efi::Event) -> Result<(), EfiError> {
         let id = event as usize;
-        self.events.remove(&id).ok_or(EfiError::InvalidParameter)?;
+        if (id & Self::RT_EVENT) != 0 {
```
Comment (os-d) [inline patina_dxe_core/src/event_db.rs:349]: Do we need the RT_EVENT tag that artifically reduces the EVENT space (yes from an absolutely enormous number)? Seems like the only thing it is used for is this check here and we could do the same check that we did to set this (e.g. 

```rust
let runtime =
            (event_type & efi::EVT_RUNTIME) != 0 || event_group == Some(efi::EVENT_GROUP_VIRTUAL_ADDRESS_CHANGE);
```

Could be a macro if we want. Not a big deal to keep the tag, but seems simpler and not having to reduce the event space to not have it?

Comment (cfernald) [reply patina_dxe_core/src/event_db.rs:349]: We don't know the event type here, until we know what list to search. We could search both, but I feel like it's better to enforce the expectation this way.

Comment (os-d) [reply patina_dxe_core/src/event_db.rs:349]: Oh, I was mixing up efi::event and struct Event, that does have this info. This is fine and I prefer to just pass an id to the caller instead of the actual pointer to the struct event.

File: patina_dxe_core/src/runtime.rs (hunk 2 above)
Comment (cfernald) [reply patina_dxe_core/src/runtime.rs:47]: Yeah, This falls under the category of "lets use rusty things when we can" nothing external needs to consume that C structure, so lets not use it.

Comment (Javagedes) [reply patina_dxe_core/src/runtime.rs:47]: Yeah my main concern on the latter half of the question was targeted about consumers of the runtime protocol. Thanks for clarifying that is not a concern.

As for the first half of the question, is there a reason you put it in its own static instead of as a member in runtime data?

**Comment by kuqin12** [comment]
Tested on hardware platform and looks good as well.
