### PR TITLE
Fix AArch64 NUM_EXCEPTION_TYPES off-by-one bug

### LINKED ISSUE #1267: [Bug]: Arch64 NUM_EXCEPTION_TYPES off-by-one
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

`NUM_EXCEPTION_TYPES` for AArch64 is `3` but should be `4`.

The assembly (`exception_handler.asm`) defines 4 exception types (Synchronous=0, IRQ=1, FIQ=2, SError=3), but the Rust constant only allocates 3 handler slots.

When an SError occurs, the system panics:
`index out of bounds: the len is 3 but the index is 3`

Observed during warm boot when UFS hardware triggered an SError.

### Expected Behavior

SError exceptions (index 3) should be handled without panic. The handler array should have 4 slots to match the 4 AArch64 exception types.

### Steps To Reproduce

1. Build and run on AArch64 hardware
2. Perform a warm boot (reboot without full power cycle)
3. Wait for UFS/storage driver initialization
4. Observe panic when hardware triggers an SError exception

Alternatively:
- Attempt to register an SError handler (exception type 3) - it will return InvalidParameter

### Build Environment

```markdown
- Hardware: AArch64 platform with UFS storage
```

### Version Information

```text
tested on - patina workspace: 19.0.5
```

### Urgency

Low

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Nir3613**
Fixed an off-by-one bug in `NUM_EXCEPTION_TYPES` for AArch64. The constant was set to `3` but should be `4` to match the 4 exception types defined in `exception_handler.asm`:

| Index | Exception Type |
|-------|----------------|
| 0 | Synchronous |
| 1 | IRQ |
| 2 | FIQ |
| 3 | SError |

With the value of `3`, SError exceptions (index 3) caused an array out-of-bounds panic:
`index out of bounds: the len is 3 but the index is 3`

This was observed during warm boot when UFS hardware triggered an SError.

Fixes #1267 

- [x] Impacts functionality

## How This Was Tested

Verified that the constant now matches the assembly definition in `core/patina_internal_cpu/src/interrupts/aarch64/exception_handler.asm` (lines 109-112).

## Integration Instructions

N/A

### CODE REVIEW

File: core/patina_internal_cpu/src/interrupts/exception_handling.rs [hunk 1]
```diff
@@ -19,7 +19,7 @@ use super::{EfiSystemContextFactory, ExceptionContext, ExceptionType, HandlerTyp
 const NUM_EXCEPTION_TYPES: ExceptionType = if cfg!(test) || cfg!(target_arch = "x86_64") {
     256
 } else if cfg!(target_arch = "aarch64") {
-    3
+    4
```
Comment (Javagedes) [inline core/patina_internal_cpu/src/interrupts/exception_handling.rs]: The name of this const is a bit of a misnomer, though I'm not sure if it is worth renaming or reducing to 255 / 3 and accounting for that where it is used. @os-d @vineelko opinions?

Comment (makubacki) [inline core/patina_internal_cpu/src/interrupts/exception_handling.rs]: As simple as this is, I suggest there be a test to verify the expected number of types per architecture. We should not have this value change without a test failing that verifies the expectation.

Comment (cfernald) [reply core/patina_internal_cpu/src/interrupts/exception_handling.rs]: How is it a misnomer? It represents the number of potential exception types for a given architecture and isn't used as a max.

Comment (Javagedes) [reply core/patina_internal_cpu/src/interrupts/exception_handling.rs]: You are right. I misread the table as only 3 entries. Closing. Thanks.

File: core/patina_internal_cpu/src/interrupts/exception_handling.rs [hunk 2]
```diff
@@ -15,11 +15,17 @@ use crate::interrupts::EfiExceptionStackTrace;
 
 use super::{EfiSystemContextFactory, ExceptionContext, ExceptionType, HandlerType};
 
+// Architecture-specific exception type counts.
+// x86_64: 256 IDT entries
+// AArch64: 4 types (Synchronous, IRQ, FIQ, SError) - see exception_handler.asm:109-112
```
Comment (makubacki) [inline core/patina_internal_cpu/src/interrupts/exception_handling.rs]: I think the constant part of the comment is sufficient. The file and line details may become stale over time.

```suggestion
// AArch64: 4 types (Synchronous, IRQ, FIQ, SError)
```

File: core/patina_internal_cpu/src/interrupts/exception_handling.rs (hunk 1 above)
Comment (makubacki) [reply core/patina_internal_cpu/src/interrupts/exception_handling.rs]: Thanks for adding the `test_num_exception_types()` unit test. Resolving this thread.
