### PR TITLE
GCD: Increase Unit Test Coverage

### LINKED ISSUE #202: [Bug]: GCD Tests Use Invalid Addresses/Lengths
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

The existing GCD tests use non-page aligned addresses and lengths and the tests are not always testing real scenarios. These tests break when we add better correctness to the GCD. There are a lot of instances of this, so the tests have been fixed up where possible, but need to be revisited and reworked.

### Expected Behavior

The GCD tests should use page aligned addresses and lengths and test real scenarios (i.e. bits are valid for capabilities, etc.).

### Steps To Reproduce

_No response_

### Build Environment

```markdown
- OS(s):
- Tool Chain(s):
- Targets Impacted:
```

### Version Information

```text

```

### Urgency

None

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

None

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by os-d**
## Description

This commit adds more robust unit testing to the GCD code, moving the spin_locked_gcd.rs file from 68% coverage to 90% coverage.

Some functions are marked with #[coverage(off)] because they are wrapper functions or otherwise not useful/possible to meaningfully test.

Closes #202 .

- [ ] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [x] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

Unit tests pass.

## Integration Instructions

N/A.

### CODE REVIEW

File: patina_dxe_core/src/gcd/spin_locked_gcd.rs [hunk 1]
```diff
@@ -40,6 +40,188 @@ use super::{
...
+
+    Box::new(SharedMockPageTable::new(mock))
+}
+
+#[cfg(test)]
+fn get_shared_mock_page_table() -> Option<Arc<MockPageTable>> {
+    let storage = SHARED_MOCK_PAGE_TABLE.lock().unwrap();
+    storage.clone()
+}
+
```
Comment (vineelko) [inline patina_dxe_core/src/gcd/spin_locked_gcd.rs]: Should this be moved to `mod test {..}` so `#[cfg(test)]` can be removed?

Comment (os-d) [reply patina_dxe_core/src/gcd/spin_locked_gcd.rs]: I'll see if it can, the problem is the actual code has to use this in the test case. But maybe not all of this

Comment (os-d) [reply patina_dxe_core/src/gcd/spin_locked_gcd.rs]: I was able to move almost all of this

**Comment by vineelko** [comment]
I think breaking

`pub(crate) fn init_paging(&self, hob_list: &HobList)`
into
`fn init_paging_with(&self, hob_list: &HobList, page_table: Box<dyn PatinaPageTable>)`

would significantly simplify the test code setup. The normal code would continue to call `init_paging()` as usual, which would invoke `create_cpu_paging()` from the `patina_internal_cpu::paging` crate and then forward the call to `init_paging_with()`. But the test code could directly call `init_paging_with(.., mocked_page_table)` with a mocked page table, eliminating the need for hacks in the `use` statements.

After that, the second problem of sharing the mocked page object between the real code and test code can also be solved without relying on `Arc`, global locks, *mut pointers, unsafe. Instead of wrapping every inner field in a `RefCell`, we can declare the inner as `inner: Rc<RefCell<..>>`, similar to what we did in the paging crate’s test code.

File: patina_dxe_core/src/gcd/spin_locked_gcd.rs [hunk 2]
```diff
@@ -4399,4 +4595,661 @@ mod tests {
...
+            assert_eq!(bad_alloc, Err(PtError::InvalidParameter), "Should fail to allocate with bad alignment");
+
+            // fail to allocate a zero sized page
+            let zero_alloc = allocator.allocate_page(UEFI_PAGE_SIZE as u64, 0, false);
+            assert_eq!(zero_alloc, Err(PtError::InvalidParameter), "Should fail to allocate zero sized page");
+        });
+    }
+
+    #[test]
+    #[should_panic]
```
Comment (Javagedes) [inline patina_dxe_core/src/gcd/spin_locked_gcd.rs:4673]: nit:


```suggestion
    #[should_panic(expected = "<something>"]
```

File: patina_dxe_core/src/gcd/spin_locked_gcd.rs [hunk 3]
```diff
@@ -4399,4 +4595,661 @@ mod tests {
...
+                    reserved: [0; 4],
+                },
+                module_name: guids::DXE_CORE,
+                entry_point: dxe_core_base as u64 + 0x1000,
+            });
+            let mut hob_list = HobList::new();
+            hob_list.push(hob);
+
+            // SAFETY: We just allocated this memory, write mock PE header data directly to memory
+            let pe_header_data = [
```
Comment (Javagedes) [inline patina_dxe_core/src/gcd/spin_locked_gcd.rs:4821]: even though you only use this once, this might be better as test collateral. We also already have some pe images in there. Is this one special or could you just re-use the exiting pe?

**Comment by os-d** [comment]
> I think breaking
> 
> `pub(crate) fn init_paging(&self, hob_list: &HobList)` into `fn init_paging_with(&self, hob_list: &HobList, page_table: Box<dyn PatinaPageTable>)`
> 
> would significantly simplify the test code setup. The normal code would continue to call `init_paging()` as usual, which would invoke `create_cpu_paging()` from the `patina_internal_cpu::paging` crate and then forward the call to `init_paging_with()`. But the test code could directly call `init_paging_with(.., mocked_page_table)` with a mocked page table, eliminating the need for hacks in the `use` statements.
> 
> After that, the second problem of sharing the mocked page object between the real code and test code can also be solved without relying on `Arc`, global locks, *mut pointers, unsafe. Instead of wrapping every inner field in a `RefCell`, we can declare the inner as `inner: Rc<RefCell<..>>`, similar to what we did in the paging crate’s test code.

I think that's fine, it is just kicking the testing can up the stack, but in this case we have the spin locked GCD wrapper for this function that I've already marked as coverage off, so we can do this there.

File: patina_dxe_core/src/gcd/spin_locked_gcd.rs (hunk 3 above)
Comment (os-d) [reply patina_dxe_core/src/gcd/spin_locked_gcd.rs:4821]: Yeah, I thought about putting this somewhere else, decided I'd wait and see if anyone complained :). Nothing special except that it is DXE core's GUID and I had to have copilot do a lot of shifting of offsets to make it fit within the allocated range. I'll check and see what we already have and either move this to the collateral or use something existing

File: patina_dxe_core/src/gcd/spin_locked_gcd.rs (hunk 2 above)
Comment (os-d) [reply patina_dxe_core/src/gcd/spin_locked_gcd.rs:4673]: Ah thanks, I was wondering if that existed. I also just filed an issue to disable debug_asserts in test code.

**Comment by os-d** [comment]
> > I think breaking
> > `pub(crate) fn init_paging(&self, hob_list: &HobList)` into `fn init_paging_with(&self, hob_list: &HobList, page_table: Box<dyn PatinaPageTable>)`
> > would significantly simplify the test code setup. The normal code would continue to call `init_paging()` as usual, which would invoke `create_cpu_paging()` from the `patina_internal_cpu::paging` crate and then forward the call to `init_paging_with()`. But the test code could directly call `init_paging_with(.., mocked_page_table)` with a mocked page table, eliminating the need for hacks in the `use` statements.
> > After that, the second problem of sharing the mocked page object between the real code and test code can also be solved without relying on `Arc`, global locks, *mut pointers, unsafe. Instead of wrapping every inner field in a `RefCell`, we can declare the inner as `inner: Rc<RefCell<..>>`, similar to what we did in the paging crate’s test code.
> 
> I think that's fine, it is just kicking the testing can up the stack, but in this case we have the spin locked GCD wrapper for this function that I've already marked as coverage off, so we can do this there.

I did this, but all we really did was drop an `A` :). I.e. we went from `Arc` to `Rc`, so I'm not sure how big of a difference that really was, but it did constrain it all to the test module and let us drop the globals, so that is good.

File: patina_dxe_core/src/gcd/spin_locked_gcd.rs (hunk 3 above)
Comment (os-d) [reply patina_dxe_core/src/gcd/spin_locked_gcd.rs:4821]: I decided to leave this in place because it is specific to this test, to make the init_paging manipulations of it work.

File: patina_dxe_core/src/gcd/spin_locked_gcd.rs (hunk 2 above)
Comment (os-d) [reply patina_dxe_core/src/gcd/spin_locked_gcd.rs:4673]: Also not doing this, because with_locked_state captures this and always has the same error

image

Let's fix this the right way and disable debug_asserts for tests and actually test production flows.

**Comment by vineelko** [comment]
> > > I think breaking
> > > `pub(crate) fn init_paging(&self, hob_list: &HobList)` into `fn init_paging_with(&self, hob_list: &HobList, page_table: Box<dyn PatinaPageTable>)`
> > > would significantly simplify the test code setup. The normal code would continue to call `init_paging()` as usual, which would invoke `create_cpu_paging()` from the `patina_internal_cpu::paging` crate and then forward the call to `init_paging_with()`. But the test code could directly call `init_paging_with(.., mocked_page_table)` with a mocked page table, eliminating the need for hacks in the `use` statements.
> > > After that, the second problem of sharing the mocked page object between the real code and test code can also be solved without relying on `Arc`, global locks, *mut pointers, unsafe. Instead of wrapping every inner field in a `RefCell`, we can declare the inner as `inner: Rc<RefCell<..>>`, similar to what we did in the paging crate’s test code.
> > 
> > 
> > I think that's fine, it is just kicking the testing can up the stack, but in this case we have the spin locked GCD wrapper for this function that I've already marked as coverage off, so we can do this there.
> 
> I did this, but all we really did was drop an `A` :). I.e. we went from `Arc` to `Rc`, so I'm not sure how big of a difference that really was, but it did constrain it all to the test module and let us drop the globals, so that is good.

Sorry for the delay, Thanks for the change, Oliver, 

I think you did much more than dropping 'A' :-)
1. You got rid of the `use` hack
2. Introduced the `_with` method, 
3. Deleted `setup_shared_mock_page_table()` and `get_shared_mock_page_table()`
4. Remove the unsafe blocks around `inner_ptr`
5. Dropped the unnecessary global locks.

One other change we could have included is dropping the `RefCell` from all the fields of `MockPageTable`. Since the inner value is already behind a `RefCell`, we don’t need field level `RefCell`. 

But this is a huge improvement. Thanks.
