### PR TITLE
Fix #176: Reject images when memory protections fail

### LINKED ISSUE #176: [Bug]: Don't attempt to reload images that memory protections failed to apply to
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

Currently, if memory protections cannot be applied, some code paths will log an error and continue. For example:

https://github.com/pop-project/uefi-dxe-core/blob/93e7b5246ae81922cd2315cd22b02a3f29261f8e/dxe_core/src/image.rs#L343-L359

### Expected Behavior

This issue tracks not loading the image again per the note in this [comment](https://github.com/pop-project/uefi-dxe-core/pull/175/files/dd048c7dc03b273a3bec385ad0aaf477c3cb1e20#r1854605388).

### Steps To Reproduce

_No response_

### Build Environment

```markdown
- OS(s):
- Tool Chain(s):
- Targets Impacted:
```

### Version Information

```text

```

### Urgency

Low

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

None

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by garybeihl**
## Description

Fixes #176

This commit changes apply_image_memory_protections() to return a Result and propagates the error up to core_load_pe_image(). If memory protections cannot be applied to any section, the entire image load fails with an error.

---

Previously, when apply_image_memory_protections() failed to set memory space attributes for an image section, the error was logged but the image continued to load. This security risk allowed images to run without proper authentication.

This commit changes apply_image_memory_protections() to return a Result and propagates the error up to core_load_pe_image(). If memory protections cannot be applied to any section, the entire image load fails with an error.

Changes:
- Modified apply_image_memory_protections() signature to return Result<(), EfiError>
- Added error propagation when core_set_memory_space_attributes() fails
- Updated call site in core_load_pe_image() to use the ? operator
- All existing tests (383) pass successfully

---

- [X] Impacts functionality?
- [X] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

Ran and passed patina_dxe_core test suite

## Integration Instructions

N/A

### CODE REVIEW

File: patina_dxe_core/src/image.rs
Comment (os-d) [inline patina_dxe_core/src/image.rs:423]: We should also return an error here

Comment (os-d) [inline patina_dxe_core/src/image.rs:405]: We should also return an error here

**Comment by cfernald** [comment]
I think a sentence got cut off in the description: "This security risk allowed images to run without proper."

File: patina_dxe_core/src/image.rs [hunk 1]
```diff
@@ -442,11 +442,15 @@ fn apply_image_memory_protections(pe_info: &UefiPeInfo, private_info: &PrivateIm
 
         match dxe_services::core_set_memory_space_attributes(section_base_addr, aligned_virtual_size, attributes) {
             Ok(_) => continue,
-            Err(status) => log::error!(
-                "Failed to set GCD attributes for image section {section_base_addr:#X} with Status {status:#X?}",
-            ),
+            Err(status) => {
+                log::error!(
+                    "Failed to set GCD attributes for image section {section_base_addr:#X} with Status {status:#X?}",
```
Comment (Javagedes) [inline patina_dxe_core/src/image.rs:446]: The idiomatic way to peek at the error before continuing to bubble it up is to use Result's `inspect_err` method

```rust
dxe_services::core_set_memory_space_attributes(section_base_addr, aligned_virtual_size, attributes)
    .inspect_err(|e| {
        log::error!("Failed to set GCD attributes for image section {section_base_addr:#X} with Status {status:#X?}")
    })?;
```

**Review by Javagedes — APPROVED** [review]

**Comment by cfernald** [comment]
Please address Oliver's comments, but otherwise looks good.

File: patina_dxe_core/src/image.rs
Comment (garybeihl) [reply patina_dxe_core/src/image.rs:423]: Good catch - thanks! - fixed

**Comment by garybeihl** [comment]
> I think a sentence got cut off in the description: "This security risk allowed images to run without proper."

Fixed - thanks!

File: patina_dxe_core/src/image.rs (hunk 1 above)
Comment (garybeihl) [reply patina_dxe_core/src/image.rs:446]: Thank you! Good to learn something new - added the .inspect_err method

File: patina_dxe_core/src/image.rs
Comment (garybeihl) [reply patina_dxe_core/src/image.rs:405]: Fixed - thanks!

**Review by joschock — APPROVED** [review]

**Review by makubacki — APPROVED** [review]

**Comment by makubacki** [comment]
I will override the patch coverage check in this case and file an issue for improved unit test coverage in the module.

**Comment by garybeihl** [comment]
Thanks - I'll work on tests next week....

**Comment by makubacki** [comment]
> Thanks - I'll work on tests next week....

Thanks! In that case, I assigned the issue to you.
